name: Flutter Continuos Integration (CI)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.6'
          cache: true
          cache-key: flutter-3.22.6
      - run: flutter pub get
      - run: flutter analyze